package com.jarvis.assistant.tools

/**
 * Risk classification for JARVIS tools.
 * - LOW: Automatically executed when technically permitted.
 * - MEDIUM: Supports or requires confirmation flow.
 * - HIGH: Requires explicit user confirmation and restricted execution constraints.
 */
enum class RiskLevel {
    LOW,
    MEDIUM,
    HIGH
}

/**
 * Standard structured result of an executed tool action.
 */
data class ToolResult(
    val success: Boolean,
    val message: String,
    val data: Map<String, Any?> = emptyMap()
)

/**
 * Structured tool request generated by the AI model or internal intent matcher.
 */
data class ToolCall(
    val name: String,
    val arguments: Map<String, Any?> = emptyMap(),
    val callId: String? = null
)

/**
 * Wrapped execution response linking tool name and outcome.
 */
data class ToolExecutionResponse(
    val toolName: String,
    val result: ToolResult
)

/**
 * Base contract that every approved JARVIS tool must implement.
 * The LLM never executes code directly; all actions pass through this contract.
 */
interface JarvisTool {
    val name: String
    val description: String
    val riskLevel: RiskLevel

    suspend fun execute(arguments: Map<String, Any?>): ToolResult
}
