package com.jarvis.assistant.planner

import com.jarvis.assistant.tools.RiskLevel

/**
 * Structured Task Plan generated by the AI Planner and executed by TaskExecutor.
 */
data class TaskPlan(
    val taskId: String,
    val userRequest: String,
    val steps: List<TaskStep>,
    val createdAt: Long = System.currentTimeMillis(),
    val estimatedRisk: RiskLevel = RiskLevel.LOW,
    val requiresConfirmation: Boolean = false
)

/**
 * Individual step within a TaskPlan.
 */
data class TaskStep(
    val stepId: Int,
    val action: String,
    val arguments: Map<String, Any?> = emptyMap(),
    val expectedResult: ExpectedResult? = null,
    val riskLevel: RiskLevel = RiskLevel.LOW,
    val requiresConfirmation: Boolean = false,
    val timeoutMs: Long = 3000L,
    val retryCount: Int = 1
)

/**
 * Expected post-action state for verification.
 */
data class ExpectedResult(
    val expectedPackage: String? = null,
    val expectedText: String? = null,
    val expectedScreenState: String? = null,
    val customCriteria: String? = null
)

/**
 * Result of executing a single step.
 */
data class StepExecutionResult(
    val isSuccess: Boolean,
    val stepId: Int,
    val action: String,
    val message: String,
    val observedPackage: String? = null,
    val isVerified: Boolean = false,
    val retryAttempt: Int = 0
)

/**
 * Overall outcome of a TaskPlan execution.
 */
data class TaskPlanResult(
    val isSuccess: Boolean,
    val completedSteps: Int,
    val totalSteps: Int,
    val finalMessage: String,
    val state: TaskExecutionState = TaskExecutionState.COMPLETED
)
